services:
  gemini-api:
    image: gemini-image-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - RATE_LIMIT=10
      - RATE_LIMIT_WINDOW_MS=60000
    volumes:
      - ./data:/app/data
      - ./public/generated-images:/app/public/generated-images
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped